version: '3'

services:
  mongo_base_5:
    container_name: mongo_base_5
    image: mongo:5.0.3
    restart: unless-stopped
    # network_mode: host
    logging:
      options:
        max-file: "5"
        max-size: "20m"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/data --quiet
      interval: 10s
      retries: 10
      start_period: 5s
      timeout: 20s
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongo"
      - "MONGO_INITDB_ROOT_PASSWORD=mongo
      - "MONGO_INITDB_DATABASE=mongo"
      # - "TZ=UTC-3"
    ports:
      - 27017:27017
    volumes:    
      - ./[data-dir]:/data/db 
      - ./[init-dir]:/docker-entrypoint-initdb.d # use .sh, .js, run in alphabetical order
  # application:
  #   container_name: application
  #   image: [img]
  #   depends_on:
  #     mongo_base_5:
  #       condition: service_healthy
