version: "3"

services:
  mongo_base_8:
    container_name: mongo-base-8
    image: mongo:8.0.5
    restart: unless-stopped
    # network_mode: host
    logging:
      options:
        max-file: "5"
        max-size: "20m"
    healthcheck:
      test: "mongosh --quiet --eval \"db.adminCommand({ ping: 1 })\""
      interval: 10s
      retries: 15
      start_period: 5s
      timeout: 20s
    environment:
      - "MONGO_INITDB_DATABASE=mongo"
      - "MONGO_INITDB_ROOT_USERNAME=mongo"
      - "MONGO_INITDB_ROOT_PASSWORD=mongo"
      # - "TZ=UTC" # Container default
      # - "TZ=America/Sao_Paulo"
    ports:
      - 27017:27017
    # volumes:    
    #   - ./[data-dir]:/data/db 
    #   - ./[init-dir]:/docker-entrypoint-initdb.d # use .sh, .js, run in alphabetical order
  # application:
  #   container_name: application
  #   image: [img]
  #   depends_on:
  #     mongo_base_5:
  #       condition: service_healthy
