version: "3"

# Notes:
#
# Image property usage:
#   This is a custom built image, see https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance
#
# Container startup
#   If there's no healthcheck defined, wait for the following message to appear in your logs so you can connect to the database
#   #########################
#   DATABASE IS READY TO USE!
#   #########################
#
# Healthcheck:
#   The provided healthcheck test here didn't use any version select as in other databases, because it uses the special character
#   inside of the query: SELECT * FROM v$version; and docker compose just tries to replace it with some environment variable
#   because that's how it interprets this command and there's no way to change this behavior. So to keep using this command, you can
#   add it to your .sql file on the host and sharing this volume. Then just change the script to run the desired .sql file.
# 
# Default credentials (non-changeable)
#   User is "system"
#   Database is "XE"
#   Role: Normal
#
#   User is "sys"
#   Database is "xe"
#   Role: sysdba, sysoper

services:
  orcdb_base_11_xe:
    container_name: orcdb-base-11-xe
    image: oracle/database:11.2.0.1-xe # Non-public available image
    shm_size: '2g'
    restart: unless-stopped
    # network_mode: host
    logging:
      options:
        max-file: "5"
        max-size: "20m"
    healthcheck:
      test: echo 'SELECT 1 FROM dual;' > /healthcheck.sql && echo 'EXIT;' >> /healthcheck.sql && sqlplus -l -s sys/mypass@//localhost:1521/xe as sysdba @/healthcheck.sql && rm /healthcheck.sql
      # test: echo 'SELECT 1 FROM dual;' > /healthcheck.sql && echo 'EXIT;' >> /healthcheck.sql && sqlplus -l -s sys/$$ORACLE_PWD@//localhost:1521/xe as sysdba @/healthcheck.sql && rm /healthcheck.sql
      interval: 10s
      retries: 30
      start_period: 5s
      timeout: 20s
    environment:
      - "ORACLE_PWD=mypass"
      # - "TZ=UTC" # Container default
      # - "TZ=America/Sao_Paulo"
    ports:
      - 1521:1521
    # volumes:
    #   - /[data-dir]:/u01/app/oracle/oradata
  # application:
  #   container_name: application
  #   image: [img]
  #   depends_on:
  #     orcdb_base_11_xe:
  #       condition: service_healthy
